#!/bin/sh

if npm run doc >/dev/null 2>&1
then
	if git status --porcelain | grep ' M README.md' >/dev/null 2>&1
	then
		echo 'You have unstaged README updates that need to be committed'
		git status -s
		exit 1
	fi
elif npm run check-deps >/dev/null 2>&1
then
	echo 'You have out-of-date dependencies that should be updated'
	exit 1
else
	exit 1
fi

exit 0
